server:
  port: 8080

spring:
  application:
    name: microservice-apigateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: lb://microservice-student
          predicates:
            - Path=/api/student/**

        - id: courses
          uri: lb://microservice-course
          predicates:
            - Path=/api/course/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
